'use strict';

var constants = {
    POSTBACK_TODAY: 'TODAY',
    POSTBACK_THIS_MONTH: 'THIS_MONTH',
    POSTBACK_CHANGE_CITY: 'CHANGE_CITY',
    POSTBACK_CONTINUE_WITH_CITY: 'CONTINUE_WITH_CITY',
    POSTBACK_EVENT_MUSIC: 'EVENT_MUSIC',
    POSTBACK_EVENT_SPORTS: 'EVENT_SPORTS',
    POSTBACK_EVENT_ARTS: 'EVENT_ARTS',
    POSTBACK_EVENT_VIEW_DETAILS: 'EVENT_VIEW_DETAILS',
    POSTBACK_MORE_RESULTS: 'MORE_RESULTS',
    POSTBACK_NEW_SEARCH: 'NEW_SEARCH',

    EVENT_CATEGORY_MUSIC_NAME: 'Music',
    EVENT_CATEGORY_SPORTS_NAME: 'Sports',
    EVENT_CATEGORY_ART_THEATRE_NAME: 'Arts & Theatre',

    BUTTON_TYPE_POSTBACK: 'postback',
    BUTTON_TYPE_WEB_URL: 'web_url'
};

module.exports = constants;
